version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.17-browsers
    steps:
      - checkout
      - run: yarn install
      - run:
          name: "Lint"
          command: yarn lint
      - run:
          name: "Test"
          command: "yarn test"
      - run:
          name: "Run Jest and Collect Coverage Reports"
          command: yarn test --coverage --collectCoverage=true
      - store_artifacts:
          path: coverage